<?php
/**
 * Created by PhpStorm.
 * User: Serg
 * Date: 16/04/2020
 * Time: 20^38
 */

namespace common\modules\catalog\models;


use yii\base\Model;
use yii\db\ActiveRecord;
use yii\web\UploadedFile;

class Review extends ActiveRecord
{
    var $file;

    public static function tableName()
    {
        return 'public.review';
    }


    public function rules()
    {
        return [
            [
                [
                    'big_img_src',
                    'small_img_src',
                    'full_text',
                    'preview_text',
                    'name',
                    'type',
                    'url',
                ],
                'string'
            ],
            [['date'], 'date', 'format' => 'd-m-Y'],
            [['file'],
                'file',
                //'skipOnEmpty' => false,
                'checkExtensionByMimeType' => false, //bug #6148
                //'extensions' => $allowedExtensions,
                'maxFiles' => 1],
            [['id','big_img_width', 'big_img_height', 'small_img_width', 'small_img_height', 'sort'], 'integer'],
            [['sort'], 'default', 'value'=> 100],
        ];
    }

    public function beforeDelete()
    {
        try {
            $docRoot = $_SERVER['DOCUMENT_ROOT'];

            if (!empty($this->getAttribute('big_img_src'))) {
                unlink($docRoot.$this->getAttribute('big_img_src'));
            }
            if (!empty($this->getAttribute('small_img_src'))) {
                unlink($docRoot.$this->getAttribute('small_img_src'));
            }
        } catch (\Exception $e) {}

        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {
        if (!parent::beforeSave($insert)) {
            return false;
        }

        /**
         *  @TODO Здесь надо генерить миникартинку
         * пока что миникартинка = большой картинке
         *
         */
        $this->small_img_src = $this->big_img_src;



        if(!empty($this->full_text)){

            $this->full_text = htmlentities($this->full_text);
        }

        if(!empty($this->preview_text)){

            $this->full_text = htmlentities($this->full_text);
        }



        //\Yii::$app->pr->print_r2($insert);

        // ...custom code here...
        return true;
    }



    public function upload()
    {

        $folder =  $_SERVER['DOCUMENT_ROOT'].'/upload/review/'; //$_SERVER['DOCUMENT_ROOT'] = /webapp

        if ($this->validate()) {
            $filePath = $folder . $this->file->baseName . '.' . $this->file->extension;

            $this->file->saveAs($filePath);

            $imgResult = getimagesize($filePath);
            $imgResult['big_img_src'] = '/upload/review/'. $this->file->baseName . '.' . $this->file->extension;


            return $imgResult;
        } else {
            return false;
        }
    }


    public function __get($name) {
        switch ($name ) {
            case 'name':
                return html_entity_decode($this->getAttribute('name'));
                break;

            case 'date':
                //return date('d.m.Y', strtotime($this->getAttribute('date')));
                break;
            case 'preview_text':

                return html_entity_decode($this->getAttribute('preview_text'));
                break;

            case 'full_text':

                return html_entity_decode($this->getAttribute('full_text'));
                break;

        }


        return parent::__get($name);
    }


    public function saveMe(){

        $model = $this;

        //\Yii::$app->pr->print_r2($model->getAttributes());
        //die();

        $attributes = [
            'name' => $model->name,
            'type' => $model->type,
            'sort' => $model->sort,
            'url' => $model->url,
            'full_text' => $model->full_text,
            'preview_text' => $model->preview_text,
        ];

        $model->file = UploadedFile::getInstance($model, 'file');

        if(!empty($model->file)){

            $savedImgResult = $model->upload();

            if ($savedImgResult) {

                //\Yii::$app->pr->print_r2($model->getAttributes());
                $attributes['big_img_src'] = $savedImgResult['big_img_src'];
                $attributes['big_img_width'] = $savedImgResult[0];
                $attributes['big_img_height'] = $savedImgResult[1];
            }

        }

        //если обновляем запись, то подменяем текущую модель той которую обновляем
        if(isset($model->id) && $model->id > 0 && !empty($model->id)){
            $model = self::findOne($model->id);

        }else{
            //SiC bug null != empty...
            unset($model->id);
        }

        $model->setAttributes($attributes);

        $model->save();

        //\Yii::$app->pr->print_r2($model->getAttributes());
        //die();

        return $model;


    }


    /*public function massUpload()
    {

        $catalogModule = \Yii::$app->getModule('Catalog');
        $catalogModule->params['csvFolderName'];

        if ($this->validate()) {

            foreach ($this->csvFile as $file) {
                $file->saveAs(__DIR__.'/upload_csv/' . $file->baseName . '.' . $file->extension);
            }
            return true;
        } else {
            return false;
        }
    }*/

}