<?php
/**
 * Created by PhpStorm.
 * User: Serg S
 * Date: 09.11.19
 * Time: 14:38
 */

namespace common\modules\catalog\models\seo;

use yii\base\Model;
use yii\db\ActiveRecord;
use yii\web\UploadedFile;


class SeoSection extends ActiveRecord
{
    var $file;

    public static function tableName()
    {
        return 'public.seo_section';
    }

    public function rules()
    {
        return [
            [['text', 'name'],'string'],

            [
                [
                    'text',
                    'name'
                ],
                'string'
            ],
            [['id','section_id', 'sort'], 'integer'],
        ];
    }

    public function beforeDelete()
    {
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {
        if (!parent::beforeSave($insert)) {
            return false;
        }

        if(!empty($this->text)) {
            $this->text = htmlentities($this->text);
        }
        return true;
    }


    public function __get($name) {
        switch ($name ) {
            case 'text':
                return html_entity_decode($this->getAttribute('text'));
                break;
        }

        return parent::__get($name);
    }


    public function saveMe(){
        $model = $this;

        //\Yii::$app->pr->print_r2($model->getAttributes());
        //die();
        $attributes = [
            'text' => $model->text,
            'name' => $model->name,
            'section_id' => $model->section_id,
        ];

        //если обновляем запись, то подменяем текущую модель той которую обновляем
        if(isset($model->id) && $model->id > 0 && !empty($model->id)){
            $model = self::findOne($model->id);
        }else if(isset($model->section_id) && $model->section_id > 0 && !empty($model->section_id)){
            $searchForUpsert = self::findOne(['section_id' => $model->section_id]);

            if (!empty($searchForUpsert)) {
                $model = $searchForUpsert;
            } else {
                //SiC bug null != empty...
                unset($model->id);
            }
        } else {
            //SiC bug null != empty...
            unset($model->id);
        }

        //\Yii::$app->pr->print_r2($model->getAttributes());
        //die();
        $model->setAttributes($attributes);

        try {
            $model->save();
        } catch (\Exception $e) {
            $model->addError($model->id, $e->getMessage());
        }

        return $model;

    }

    /**
     * @param $manufacturerId
     */
    public static function getTextBySectionId($sectionId) {
        if (!empty($sectionId)) {
            $foundOne = parent::findOne(['section_id' => $sectionId]);
        }

        if ($foundOne) {
            return $foundOne->text;
        }

        return '';
    }
}